# Generated by Django 4.2.4 on 2023-08-31 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
