# Generated by Django 4.2.4 on 2023-09-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Phone_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
